"""Add supabase_id to User

Revision ID: 9d7d8fa73b42
Revises: 
Create Date: 2025-12-30 23:47:54.947431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d7d8fa73b42'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('method', sa.Enum('MANUAL', 'IN_APP', name='paymentmethod'), nullable=True))
    op.add_column('user', sa.Column('supabase_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_supabase_id'), 'user', ['supabase_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_supabase_id'), table_name='user')
    op.drop_column('user', 'supabase_id')
    op.drop_column('payment', 'method')
    # ### end Alembic commands ###
